### ISSUE TITLE
Various district and school IDs

### ISSUE THREAD

**Issue by eyeseast** [LearningLab/public-schools#2]
Here are the identifiers I've seen for schools and districts:
- NCES
- state DOE (DESE, in Massachusetts)
- DonorsChoose
- GreatSchools.org

What else is out there? What's unique enough that it could potentially be a primary key?

**Comment by vmorrisPolar** [comment]
Hi There @eyeseast has this project been abandoned?

**Comment by eyeseast** [comment]
Yes. This was part of an old project that has since been merged into WBUR's main education coverage. I should archive it.

**Comment by vmorrisPolar** [comment]
Is the resulting list publicly available, or no?
